#
# Debian-style network interface writer for Ubuntu/Debian targets
#
# Copyright (C) 2026
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#

import os
import ipaddress
import configparser

from pyanaconda.anaconda_loggers import get_module_logger
from pyanaconda.core.path import make_directories

log = get_module_logger(__name__)

DEBIAN_INTERFACES_DIR = "/etc/network/interfaces.d"


def write_debian_interface_config(root, device_name, connection_settings):
    """Write Debian-style interface configuration.

    :param root: path to the root of the target system
    :param device_name: network device name (e.g., eth0)
    :param connection_settings: NetworkManager connection settings dict
    :return: True if successful, False otherwise
    """
    try:
        target_dir = os.path.join(root, DEBIAN_INTERFACES_DIR.lstrip('/'))
        make_directories(target_dir)

        config_file = os.path.join(target_dir, f"ifcfg-{device_name}")

        # Extract IPv4 settings
        ipv4_settings = connection_settings.get('ipv4', {})
        ipv4_method = ipv4_settings.get('method', 'auto')

        content_lines = [f"# Generated by Anaconda for {device_name}"]

        # Auto-start interface on boot
        content_lines.append(f"auto {device_name}")

        # Configure based on method
        if ipv4_method == 'manual':
            content_lines.append(f"iface {device_name} inet static")

            # Get IP address
            address_data = ipv4_settings.get('address-data', [])
            if address_data:
                addr_info = address_data[0]
                address = addr_info.get('address')
                prefix = addr_info.get('prefix', 24)

                if address:
                    content_lines.append(f"    address {address}")
                    # Calculate netmask from prefix
                    netmask = str(ipaddress.IPv4Network(f"0.0.0.0/{prefix}", strict=False).netmask)
                    content_lines.append(f"    netmask {netmask}")

            # Gateway
            gateway = ipv4_settings.get('gateway')
            if gateway:
                content_lines.append(f"    gateway {gateway}")

            # DNS servers
            dns_data = ipv4_settings.get('dns-data', [])
            if dns_data:
                dns_servers = ' '.join(dns_data)
                content_lines.append(f"    dns-nameservers {dns_servers}")

        else:
            # DHCP or auto
            content_lines.append(f"iface {device_name} inet dhcp")

        # Write the file
        content = '\n'.join(content_lines) + '\n'
        with open(config_file, 'w') as f:
            f.write(content)

        log.info("Created Debian-style network config: %s", config_file)
        return True

    except Exception as e:
        log.error("Failed to write Debian interface config for %s: %s", device_name, str(e))
        return False


def convert_nm_to_debian_interfaces(root, nm_connections_dir="/etc/NetworkManager/system-connections"):
    """Convert NetworkManager keyfile connections to Debian interfaces format.

    :param root: path to the root of the target system
    :param nm_connections_dir: path to NM connections directory
    :return: number of interfaces converted
    """
    converted = 0
    nm_dir = os.path.join(root, nm_connections_dir.lstrip('/'))

    if not os.path.exists(nm_dir):
        log.warning("NetworkManager connections directory not found: %s", nm_dir)
        return 0

    for filename in os.listdir(nm_dir):
        if not filename.endswith('.nmconnection'):
            continue

        filepath = os.path.join(nm_dir, filename)
        try:
            # Parse NM keyfile using ConfigParser
            config = configparser.ConfigParser()
            config.read(filepath)

            # Get interface name from connection section
            if not config.has_section('connection'):
                log.debug("Skipping %s: no connection section", filename)
                continue

            interface_name = config.get('connection', 'interface-name', fallback=None)
            if not interface_name:
                log.debug("Skipping %s: no interface-name", filename)
                continue

            # Build settings dict
            settings = {}

            # Parse IPv4 settings
            if config.has_section('ipv4'):
                ipv4 = {}
                ipv4['method'] = config.get('ipv4', 'method', fallback='auto')

                # Parse addresses (format: "address/prefix")
                addr_data = []
                address1 = config.get('ipv4', 'address1', fallback=None)
                if address1:
                    # Format is typically "10.191.6.73/24,10.191.6.1"
                    parts = address1.split(',')
                    if parts:
                        addr_parts = parts[0].split('/')
                        if len(addr_parts) >= 2:
                            addr_data.append({
                                'address': addr_parts[0],
                                'prefix': int(addr_parts[1])
                            })

                if addr_data:
                    ipv4['address-data'] = addr_data

                # Gateway (might be in address1 after comma, or separate)
                if address1 and ',' in address1:
                    gateway = address1.split(',')[1].strip()
                    ipv4['gateway'] = gateway
                else:
                    gateway = config.get('ipv4', 'gateway', fallback=None)
                    if gateway:
                        ipv4['gateway'] = gateway

                # DNS servers (format: "10.5.5.5;10.5.5.6;")
                dns_str = config.get('ipv4', 'dns', fallback=None)
                if dns_str:
                    dns_data = [d.strip() for d in dns_str.rstrip(';').split(';') if d.strip()]
                    if dns_data:
                        ipv4['dns-data'] = dns_data

                settings['ipv4'] = ipv4

            # Write Debian config
            if write_debian_interface_config(root, interface_name, settings):
                converted += 1
                log.info("Converted %s to Debian interface config", interface_name)

        except Exception as e:
            log.error("Failed to convert %s: %s", filename, str(e))
            continue

    log.info("Converted %d NetworkManager connections to Debian format", converted)
    return converted
